# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Documentation
company: Company
companyurl: https://batary.io
email: webmaster@company.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for our platform 📃
baseurl: "/jekyll-docs" # the subpath of your site, e.g. /blog
url: "https://batary.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  some-product:
    title: Some product
    description: Get stuff done blazing fast with this.
    illustration: user-astronaut
    output: true
    permalink: /:collection/:name
  another-product:
    title: Another product
    description: This other product is also really useful.
    illustration: space-shuttle
    output: true
    permalink: /:collection/:name

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
